on:
  pull_request:
    branches:
      - master

name: checks

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install node_modules
        run: npm i

      - name: Typecheck
        run: npm run tsc

      - name: Lint
        run: npm run lint -- src

      - name: Test
        run: npm run test

      - name: Build
        run: |
          npm run build
          npm run sb:build

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
