on:
  pull_request:
    branches:
      - master

name: checks

env:
  NODE_VERSION: 14

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install node_modules
        run: npm i

      - name: Build
        run: npm run build

      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
